apiVersion: v1
kind: Namespace
metadata:
  name: ml-training
  labels:
    app.kubernetes.io/part-of: transformer-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-inference
  labels:
    app.kubernetes.io/part-of: transformer-platform
